fc out1.txt output_brain_check1.txt
fc out2.txt output_brain_check2.txt
fc out3.txt output_dilate_rectangle.txt
fc out4.txt output_erode_rectangle.txt
fc out5.txt output_spot.txt
fc out6.txt output_spots.txt
fc out7.txt output_cat.txt
fc out8.txt output_errors.txt
fc out9.txt output_invalid_args1.txt
fc out10.txt output_invalid_args2.txt
fc out11.txt output_invalid_args3.txt
fc out12.txt output_x-file.txt
fc out13.txt output_too_colourful.txt
fc out14.txt output_too_short.txt
fc out15.txt output_too_tall.txt
fc out16.txt output_too_thin.txt
fc out17.txt output_too_wide.txt
fc out18.txt output_too_twisted.txt 
